# Generated by Django 5.2.1 on 2026-01-27 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_asst', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='delete_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_deleted',
            field=models.SmallIntegerField(default=0, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='theme',
            name='delete_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='theme',
            name='is_deleted',
            field=models.SmallIntegerField(default=0, verbose_name='是否删除'),
        ),
    ]
