# Generated by Django 5.2.1 on 2026-01-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_asst', '0002_conversation_delete_time_conversation_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='image_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='图片URL'),
        ),
    ]
