# Generated by Django 5.2.1 on 2026-01-29 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet_asst', '0003_conversation_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
